### ISSUE TITLE
Client doesn't recognize it's in a PvP world when using quick launch args.

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#310]
Client doesn't recognize it's in a PvP world when the world is specified by quick launch arguments. 

For example, if a PvP world is set as the world using quick launch arguments, the client will successfully login to the PvP world, but not recognize it as a PvP world, therefore, making bank chests and such in PvP worlds useless and only using regular banks.

In order to resolve this, you have to manually select the PvP world on the login screen or manually hop to a PvP world using the world hopper. After doing so, the client will then recognize the player is in a PvP world and use the PvP world features such as bank chests properly.

**Comment by SPEN-CER** [comment]
I've already fixed this for the next build. The problem was that the game engine doesn't populate the worlds array until it is needed. This also broke the world hopper in some circumstances, since the worlds api would try to find the world before attempting to open the world hopper, but wouldn't as a result of not finding the world. Manually opening the world hopper prior was a workaround

I've been able to fix it by making RSPeer force load world data. This update will be released either tomorrow or on Thursday around the time that the normal weekly game update hits.
