### ISSUE TITLE
Universal Bank.open() method

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#34]
I've let Malik know about this and given him some bank location enums to work off.

Will be even easier to work with once web is complete but still possible to do at the moment.

**Comment by SPEN-CER** [comment]
This could be improved a little by using object.getDefinition().getMapFunction() - this returns an int representing the minimap icon. Since npcs can only be loaded as far as the minimap icon, if no object or npc is found, then it should walk towards the nearest object with a bank minimap icon. 

With that being said, the web is near so we'll be implementing a better solution with that
