### ISSUE TITLE
Instance tracking system is inefficient

### ISSUE THREAD

**Issue by BitScorpio** [rs-peer/issues#390]
Just suffered from a power outage, which lasted for like 15 minutes. The instance tracker shuts the bot down if it cannot connect to the RSPeer server within 5 minutes. Had to re-open the client and launch my script when electricity came back.

**Comment by MaddoxDevelopment** [comment]
This isn't really an issue, we have to verify you are connected to the server to be able to validate your instances. I, unfortunately, can't change the entire system because you suffered a power outage once, that is not a common thing to happen.

The best I could do is make the threshold higher, possibly 20 minutes instead of 5.
