### ISSUE TITLE
Improve item listener

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#43]
Not sure how to use it.

Wondering if its possible to directly retrieve the item that has changed?

**Comment by SPEN-CER** [comment]
Unfortunately this isn't possible at the moment. Since `ItemTableEvent` occurs on an ItemTable, the only data that we have to work with is the stack size, id, slot and table key. Retrieving the Item object means the event would need to know the component that the event occured on. I am not aware of any way to map table key to component uids, so unless every table key is mapped, I will not be able to provide a reliable method to do this. One solution that comes to mind is to inject elsewhere, but this may be a little more complicated, and it may break existing implementations of the listener, so I would like to avoid this.

For the next build, I've added a `getTableKey` function. With this you can check what item table the event occured on (bank, inventory, equipment etc). Constants for known tables are available in the ItemTables class
